### PR TITLE
C structures refactoring : Rename/elim some tsk_id_t typedefs; rename data members

### LINKED ISSUE #1121: C structures refactoring
There's a number of long-standing refactoring issues noted at the top of [msprime.h](https://github.com/tskit-dev/msprime/blob/master/lib/msprime.h#L66).

- [ ] Get rid of the population_id_t, label_id_t typedefs and use tsk_id_t everywhere instead.
- [ ] Change segment_t.population_id to segment_t.population
- [ ] Change node_mapping_t.left to node_mapping_t.position.
- [ ] Change sweep_t.locus to sweep_t.position

This would be a good issue for someone looking to get familiar with the C code.

### LINKED ISSUE #1145: requirements/readthedocs.txt missing sphinx_rtd_theme
In building a minimal container image that can make the msprime docs, I call
```
pip3 install -r requirements/readthedocs.txt
```
but results in:
```
(ubuntu-18.04-pip)castedo@fire:~/shr/src/msprime/docs$ make
python3 -m sphinx -b html -d _build/doctrees  -W . _build/html
Running Sphinx v3.2.1
loading pickled environment... failed
failed: build environment version not current

Theme error:
sphinx_rtd_theme is no longer a hard dependency since version 1.4.0. Please install it manually.(pip install sphinx_rtd_theme)
Makefile:52: recipe for target 'html' failed
make: *** [html] Error 2
```
I'm in the process of committing the full Dockerfile to `tskit-dev/containers` that shows all the details.

Adding `sphinx_rtd_theme` to `requirements/readthedocs.txt` fixes the problem.

Feel free to assign to me to fix.

### PR DESCRIPTION
**Pull request by castedo**
Closes #1121

  - rename/elim typedefs:
    - population_id_t
    - label_id_t
    - node_id_t
    - mutation_id_t
    - site_id_t
  - rename some struct data members:
    - tsk_id_t *.population_id -> *.population
    - node_mapping_t.left -> node_mapping_t.position.
    - sweep_t.locus -> sweep_t.position

Also:
Closes #1145

### CODE REVIEW

**Comment by castedo** [comment]
Also closes #1145

File: lib/msprime.h [hunk 1]
```diff
@@ -63,36 +63,27 @@
...
-typedef tsk_id_t node_id_t;
-typedef tsk_id_t mutation_id_t;
-typedef tsk_id_t site_id_t;
-typedef tsk_id_t label_id_t;
-
 typedef struct segment_t_t {
-    /* TODO change to population */
-    population_id_t population_id;
-    label_id_t label;
+    tsk_id_t population;
```
Comment (jeromekelleher) [inline lib/msprime.h:67]: I'm a bit hesitant about changing ``population_id_t`` and ``label_id_t``, actually, because of this struct. Once the dust settles on #1138, we might be able to make this struct a bit smaller by making population and label 16 bit (which is plenty big enough). This struct is important as we do have gazillions of them in large simulations. But, given that most things are 8 byte aligned these days I don't know if that would make any difference anyway.

**Review by jeromekelleher — COMMENTED** [review]
Looks great, thanks @castedo! If you did this with a sed script, would you mind holding off on it until after #1138 lands? There's a bunch of changes in there too, and it would be a bit easier to not deal with the merge mess.

Also, see my comment above about label and population, it might be better to back out of changing those because we could potentially save some significant space at some point by typedefing them to int16.

**Comment by castedo** [comment]
> If you did this with a sed script, would you mind holding off on it until after #1138 lands? There's a bunch of changes in there too, and it would be a bit easier to not deal with the merge mess.

The sed script with a forced push to master was more a joke. ;-) But I did use some sed lines for the first pass. Yes, let's proceed avoiding the messy merge. Better you have a clear diff with #1138 and it'll be easier for me to merge my branch after #1138 merges with master. I'm going to practice some advanced git moves and follow and work off the branch you mention in #1138.

File: lib/msprime.h (hunk 1 above)
Comment (castedo) [reply lib/msprime.h:67]: In general, makes sense to me to keep typedefs, like population_id_t and label_id_t. So I'll update to KEEP all the tsk_id_t typedefs that I initially removed in this PR.

Comment (jeromekelleher) [reply lib/msprime.h:67]: Getting rid of ``node_id_t``,  ``mutation_id_t`` and  ``site_id_t`` is good, they're definitely pointless.

**Comment by jeromekelleher** [comment]
Sounds good, thanks @castedo. I'll try and get #1138 ship-shape ASAP

File: lib/msprime.h (hunk 1 above)
Comment (castedo) [reply lib/msprime.h:67]: Good to know, I'll keep those of those three pointlessly precise typedefs out.

**Comment by castedo** [comment]
@jeromekelleher 
> But, given that most things are 8 byte aligned these days I don't know if that would make any difference anyway.
With the caveat I'm not very familiar with HPC, I'd predict most users are running x86-64 and data is aligned the same way we're building in linux containers and personal computers. I'm going to see if can tell.

**Comment by jeromekelleher** [comment]
> I'd predict most users are running x86-64

This is definitely true.

**Comment by castedo** [comment]
I'm not sure if you are wondering whether all data members will get 8 byte
aligned or just 64 bit data members will. In gdb on x86-64 I'm looking at
segment_t and I see `population`(_id) and `label` both getting placed together and
fitting within 8 bytes. However I see 32 bit `tsk_id_t value;` sitting all alone
with a 32 bit gap to the next data member `size_t id;`.

If `population_id_t` and `label_id_t` were both 16 bits and then `tsk_id_t value;`
was moved to be next to them, then I bet all data members of segment_t will be snug
and tight, and the whole struct will fit in 64 bytes rather than the current 72 bytes.

Do you use valgrind's cachegrind tool to evaluate memory cache hits?

Do you know of any easier to see how structs are laid out in memory rather than gdb printing memory addresses of data members?

**Comment by jeromekelleher** [comment]
Actually there's also #1114 that needs to go in to since tskit has just been released @castedo, so it'd be better to hold off on this until the dust has settled on this big PRs early next week. Apologies for the churn here.

**Comment by jeromekelleher** [comment]
It's just the overall size of the struct I'm thinking about @castedo - because of alignment requirements, things tend to get padded out to 8-byte multiples. Cache-hits and stuff is another level, really.

**Comment by castedo** [comment]
My hunch is that on x86-64 only 64 bit data members will get aligned to 
addresses of 8 byte multiples. As long as that 'tsk_id_t value;' in 
segment_t is next to population(_id) and label if they become 16 bit, 
then 8 bytes will get shaved off segment_t.

**Comment by castedo** [comment]
Closes #1145

**Comment by jeromekelleher** [comment]
Looks like this is merging cleanly now @castedo, so let's get it in. Can you fix the clang-format errors please?

**Comment by castedo** [comment]
It looks like github is using clang-format version 6.0 whereas Ubuntu 20.04 defaults to clang-format 10.0.
@jeromekelleher should I update the
["official" :) msprime dev container](https://github.com/tskit-dev/containers/pull/3/files#diff-22d371c5bd5a6a3b8ee9b7e772a19c7a
)
to install specifically clang-format version 6.0? or should the github version be 10?

**Review by jeromekelleher — APPROVED** [review]
Great stuff, thanks @castedo!

**Comment by jeromekelleher** [comment]
> It looks like github is using clang-format version 6.0 whereas Ubuntu 20.04 defaults to clang-format 10.0.
@jeromekelleher should I update the "official" :) msprime dev container to install specifically clang-format version 6.0? or should the github version be 10?

This is very irritating all right. I ended up installing clang-format version 6 on my Mint machine rather that fight with it. I don't know what the right approach is - I guess we should wait until the majority of people are using version 10 before upgrading our CI to it. @benjeffery, what do you think?

**Comment by benjeffery** [comment]
> This is very irritating all right. I ended up installing clang-format version 6 on my Mint machine rather that fight with it. I don't know what the right approach is - I guess we should wait until the majority of people are using version 10 before upgrading our CI to it. @benjeffery, what do you think?

We picked v6 as it was the version in the Ubuntu LTS at the time. I'm reluctant to change this on everyone until either another version is ubiquitous, or that the resultant formatted code is stable. For example if we know that v8, 9 and 10 give the same output then specifying minimum v8 makes sense - I'd need to check if this is the case though. I suspect it is not.

Debian stable is now on [v7](https://packages.debian.org/stable/clang-format), ubuntu [v10](https://packages.ubuntu.com/focal/clang-format). I think centOS is v9 and fedora v10, (looking at https://pkgs.org/search/?q=clang-format). So it seems things have moved on. Let me check which versions give identical output and I'll suggest a move if it looks wise.

**Comment by jeromekelleher** [comment]
Sounds good, thanks @benjeffery. It's surprising/a bit crap that clang-format doesn't doesn't have an option to say "use v6 formatting", that would solve all our problems.

**Comment by jeromekelleher** [comment]
Yep, looks like there's [no good way to do this](https://stackoverflow.com/questions/59395507/how-to-maintain-a-clang-format-file-for-different-clang-format-versions).

**Comment by molpopgen** [comment]
Ubuntu 20.04 has 7,8,9, and 10 available, via `apt install clang-format-X`.  Then, `update-alternatives` to have `clang-format` refer to, say, `clang-format-7`, and you may be in business.

**Comment by castedo** [comment]
> Ubuntu 20.04 has 7,8,9, and 10 available, via `apt install clang-format-X`.

and also `clang-format-6.0` for ubuntu 20.04.

**Comment by molpopgen** [comment]
> and also `clang-format-6.0` for ubuntu 20.04.

hah--I missed that b/c of the change in package number pattern.

**Comment by castedo** [comment]
@jeromekelleher in this particular case, the annoying diff is merely white space. The lint-c test could ignore white space changes. It is C after all, not Python. That run-clang-format.py in the list-c test is ~400 lines of Python which doesn't seem to do much more than these 3 single line shell functions:
```
files () { find lib -name '*.[hc]' -not -path 'lib/avl.*' -not -path 'lib/dev-tools/*' -not -path 'lib/subprojects/*'; }
clang-diff () { clang-format $1 | diff --brief $1 - ; }
run_it() { DIFF=0; for F in $(files); do clang-diff $F; let "DIFF |= $?"; done; return $DIFF; }
run_it && echo PASS || echo FAIL
```
If one inserts `--ignore-space-change` in the `diff` call then white space changes will pass.

**Comment by jeromekelleher** [comment]
It's a good idea @castedo, but it'll mean that we get noise in the diffs as those whitespace changes go back and forth each time someone edits a file (say I'm on version 6 and you're on version 7). I think we just have to standardise on clang-format 6 and be done with it.

**Comment by castedo** [comment]
Good point @jeromekelleher that continued committing of whatever `clang-forman -i` does would lead to diff noise.
I've updated the Ubuntu 20 LTS container image I develop in:
https://github.com/tskit-dev/containers/pull/3/commits/778842776c22de64c2cf9f196885505eace17b7c
to follow the approach suggested by @molpopgen  and make clang-format be version 6.0.
For those that are in a pinch with a newer clang version, using this bash function might be useful:
```
chill_format() { (clang-format $1 || cat $1) | diff --ignore-space-change $1 - | patch $1; }
```
Running `chill_format` instead of `clang-format` will drop changes in amount of whitespace by clang-format.
