### PR TITLE
Fix problem in very-low recombination DTWF.

### LINKED ISSUE #831: Runtime error with `model='dtwf'` and recombination if `length=` is too small.
This causes an immediate crash on version 0.7.3:

```
msp.simulate(10, Ne=1e3,
             model="dtwf", 
             mutation_rate=1e-8, 
             recombination_rate=1e-9
            )
```

The error message is:

> Assertion failed: (k > 0 && "Negative distance: Overflow in gsl_ran_exponential!"), function msp_dtwf_recombine, file lib/msprime.c, line 1279.

Switching to Hudson's algorithm, and/or setting the `length=` parameter to something large, behaves as expected.

### PR DESCRIPTION
**Pull request by jeromekelleher**
Closes #831.

@DomNelson, can you take a look through this please?

### CODE REVIEW

**Comment by jeromekelleher** [comment]
Ping @DomNelson --- any chance of a quick review here please?

File: lib/msprime.c [hunk 1]
```diff
@@ -1263,21 +1263,32 @@ msp_defrag_segment_chain(msp_t *self, segment_t *z)
...
+msp_dtwf_generate_breakpoint(msp_t *self, int64_t start)
+{
+    double mu = 1.0 / self->recombination_rate;
+    double x = gsl_ran_exponential(self->rng, mu);
+
+    /* Prevent overflowing into a negative number when we convert to int
+     * and clamp to UINT32_MAX since we can't have anything bigger than
+     * this anyway. */
+    x = GSL_MIN(UINT32_MAX, x);
+    assert(x >= 0);
```
Comment (DomNelson) [inline lib/msprime.c]: Any benefit to just setting `x = UINT32_MAX` if `x < 0`? We'd avoid having an assertion then, but maybe that's masking too much.

Comment (jeromekelleher) [reply lib/msprime.c]: I don't think x can be negative at this point, as gsl_ran_exponential should always return something positive. We only got negative values because we cast to an int, and the value was too large for an int64, causing it to flip negative. But, just to be sure, I stuck in an assert!
